esphome:
  name: esp1
  friendly_name: ESP1

esp8266:
  board: d1_mini

logger:

api:
  encryption:
    key: "changeit"

ota:
  password: "changeit"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Esp1 Fallback Hotspot"
    password: "changeit"

captive_portal:

# HC-SR501 PIR Sensor
binary_sensor:
  - platform: gpio
    pin: D4
    name: "PIR Sensor"
    device_class: motion

# Photoresistor (Photocell)
sensor:
  - platform: adc
    pin: A0
    name: "Photoresistor"
    update_interval: 60s
    filters:
      - multiply: 3.3
