esphome:
  name: esp2
  friendly_name: ESP2

esp8266:
  board: d1_mini

logger:

api:
  encryption:
    key: "changeit"

ota:
  password: "changeit"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Esp2 Fallback Hotspot"
    password: "changeit"

captive_portal:

remote_receiver:
  pin: D1
  dump: all
