esphome:
  name: esp3-emily
  friendly_name: ESP3-Emily

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "changeit"

ota:
  password: "changeit"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Esp3-Emily Fallback Hotspot"
    password: "KRoWrXJVM7Bx"

captive_portal:

i2c:
  sda: D2
  scl: D1
  scan: true
  id: bus_a

sensor:
  - platform: am2320
    temperature:
      name: "Desk Temperature"
    humidity:
      name: "Desk Humidity"
    update_interval: 60s
